providers = ["...", "python"]

[phases.install]
dependsOn = ["python:install"]
cmds = ["...", "pip install gunicorn[gevent]==21.2.0"]

[phases.build]
cmds = ["...", "npx tailwindcss -i ./readverse/css/main.css -o ./readverse/static/style.css"]

[start]
cmd = "gunicorn -b 0.0.0.0 -k gevent app:app"