"""empty message

Revision ID: 135272138342
Revises: 32eaa391d89a
Create Date: 2023-11-28 18:59:01.211279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '135272138342'
down_revision = '32eaa391d89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], name=op.f('fk_admin_username_user')),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_admin'))
    )
    op.create_table('regularuser',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], name=op.f('fk_regularuser_username_user')),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_regularuser'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('about')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('about', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('website', sa.VARCHAR(), nullable=False))

    op.drop_table('regularuser')
    op.drop_table('admin')
    # ### end Alembic commands ###
