"""empty message

Revision ID: 32eaa391d89a
Revises: 
Create Date: 2023-11-28 18:32:57.169060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32eaa391d89a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.username'], name=op.f('fk_story_author_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story'))
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.username'], name=op.f('fk_comment_author_id_user')),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_comment_story_id_story')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.username'], name=op.f('fk_rating_author_id_user')),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_rating_story_id_story')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('comment')
    op.drop_table('story')
    # ### end Alembic commands ###
