"""empty message

Revision ID: 5278a0f77b1d
Revises: 
Create Date: 2023-11-29 10:05:35.639657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5278a0f77b1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_user'))
    )
    op.create_table('admin',
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], name=op.f('fk_admin_username_user')),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_admin'))
    )
    op.create_table('regularuser',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.username'], name=op.f('fk_regularuser_username_user')),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_regularuser'))
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.username'], name=op.f('fk_story_author_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story'))
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.username'], name=op.f('fk_comment_author_id_user')),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_comment_story_id_story')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.username'], name=op.f('fk_rating_author_id_user')),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], name=op.f('fk_rating_story_id_story')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('comment')
    op.drop_table('story')
    op.drop_table('regularuser')
    op.drop_table('admin')
    op.drop_table('user')
    # ### end Alembic commands ###
